In [10]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

#from root
%store -r df2_dammy

In [11]:
#make a new datafram by coping <df2_dammy>
df_models = df2_dammy.copy()
print(df_models.shape)
df_models.head(2)

(4608995, 649)

,Date,Arrest,Domestic,Crimes Against,beat_no,Location Description_AIRCRAFT,Location Description_AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,Location Description_AIRPORT BUILDING NON-TERMINAL - SECURE AREA,Location Description_AIRPORT EXTERIOR - NON-SECURE AREA,Location Description_AIRPORT EXTERIOR - SECURE AREA,...,Community Area_68.0,Community Area_69.0,Community Area_70.0,Community Area_71.0,Community Area_72.0,Community Area_73.0,Community Area_74.0,Community Area_75.0,Community Area_76.0,Community Area_77.0
0,2015-09-05 13:30:00,0,1,Persons,15,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2015-09-02 02:00:00,0,1,Persons,15,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# sns.heatmap(df_models.corr(numeric_only = True), cmap='coolwarm')
# plt.show()

##### something

In [13]:
#https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.year.html
#spreads features of 'Date'
df_models['Year'] = df_models['Date'].dt.year
df_models['Month'] = df_models['Date'].dt.month
df_models['Day'] = df_models['Date'].dt.day
df_models['Hour'] = df_models['Date'].dt.hour
df_models.head(1)

#confirm

,Date,Arrest,Domestic,Crimes Against,beat_no,Location Description_AIRCRAFT,Location Description_AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,Location Description_AIRPORT BUILDING NON-TERMINAL - SECURE AREA,Location Description_AIRPORT EXTERIOR - NON-SECURE AREA,Location Description_AIRPORT EXTERIOR - SECURE AREA,...,Community Area_72.0,Community Area_73.0,Community Area_74.0,Community Area_75.0,Community Area_76.0,Community Area_77.0,Year,Month,Day,Hour
0,2015-09-05 13:30:00,0,1,Persons,15,0,0,0,0,0,...,0,0,0,0,0,0,2015,9,5,13

In [14]:
#drops the column
df_models.drop(columns='Date', inplace=True)
df_models.head(1)

#confirm

,Arrest,Domestic,Crimes Against,beat_no,Location Description_AIRCRAFT,Location Description_AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,Location Description_AIRPORT BUILDING NON-TERMINAL - SECURE AREA,Location Description_AIRPORT EXTERIOR - NON-SECURE AREA,Location Description_AIRPORT EXTERIOR - SECURE AREA,Location Description_AIRPORT PARKING LOT,...,Community Area_72.0,Community Area_73.0,Community Area_74.0,Community Area_75.0,Community Area_76.0,Community Area_77.0,Year,Month,Day,Hour
0,0,1,Persons,15,0,0,0,0,0,0,...,0,0,0,0,0,0,2015,9,5,13

#### models

In [15]:
#https://note.nkmk.me/en/python-pandas-sample/
#reduces the sample size
models_sample = df_models.sample(frac=0.1, random_state=1)
#4609145*0.01=~46K

#features
y = models_sample['Crimes Against']
#target
X = models_sample.drop(columns='Crimes Against')

#split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [16]:
#print shapes
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(345675, 651) (115225, 651)
(345675,) (115225,)

In [17]:
#a scaler
std_scaler = StandardScaler()

#fit it
std_scaler.fit(X_train)

#transform them
X_train_sca = std_scaler.transform(X_train)
X_test_sca = std_scaler.transform(X_test)

In [18]:

#creates a model: knn
knn = KNeighborsClassifier()
#fit it
knn.fit(X_train_sca, y_train)

print("train accuracy: ", knn.score(X_train_sca, y_train))
print("test accuracy: ", knn.score(X_test_sca, y_test))

# print(knn.predict(X_train_sca))
# print(knn.predict(X_test_sca))

train accuracy:  0.7292398929630434
test accuracy:  0.617678455196355